Выполнены задания 1 - 8
RealBaty/hh-school-2022-java-collections-stream pull request #1
Opened 2022-12-14 01:35 UTC by RealBaty

- В заданиях 1 - 7 написана реализация публичных методов.
- В задании 8 исправлены методы и написаны комментарии к ним
- В задании 1 сложность работы функции - O(n) + O1, где n - количество элементов в personIds, O1 - сложность работы функции personService.findPersons(personIds)

2022-12-15 10:48 UTC, genroelgvozo requested changes

2022-12-15 10:48 UTC, genroelgvozo commented on src/main/java/tasks/Task1.java
> +      personById.put(person.getId(), person);
в мапу всегда удобнее собирать через stream.collect()
да, я помню сказал фразу что "если у вас один терминальный оператор, то скорее всего что-то не так" но забыл добавить "кроме мапы", потому что там по факту читаемая замена цикла и удобное представление а что будет ключом и что будет значением

2022-12-15 10:48 UTC, genroelgvozo commented on src/main/java/tasks/Task6.java
> +                    .map(areaId -> person.getFirstName() + " - " + nameByIdAreas.get(areaId)))
выше про сборку в мапе аналогично первому.
тут в целом ок, но в идеале логику превращения в строку лучше инкапсулировать в приватный метод getPersonDescription
и более того - принимать целиком персону и арейку, чтобы сам решал какие поля нужны (ты же знаешь чем станет богаче арейка и что еще пригодится потом тут)

2022-12-15 10:48 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  а так же избавляет от необходимости проверять длину списка.
а кроме длины что еще плохо было в изначальном коде?

2022-12-15 10:48 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  - Не используется функция getNames, что позволяет повторно не раскладывать список в stream
а и не надо раскладывать список в стрим, прямо же пример из лекции))
но дублировать код точно не надо, там же может быть еще логика

2022-12-15 10:48 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +   */
а если все в две строки через стрим?)

2022-12-15 10:48 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  - Улучшена читаемость за счет отсутствия вложенных циклов
быстро - да. Читаемо - в целом чуть лучше, но иф вложенный так же

хочется прямо похоже - посмотри на anyMatch в стримах
или Collections.disjoint

2022-12-15 10:48 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  - Подсчет реализован через count() в угоду читаемости
только ли читаемости?) или еще что-то плохое было в коде?

2022-12-16 02:36 UTC, RealBaty commented on src/main/java/tasks/Task8.java
> +  а так же избавляет от необходимости проверять длину списка.
Плохо было то, что из  списка поступающего в функцию удалялся элемент. Это плохо по двум причинам:

- Это может быть долго
- Это может приводить к неприятным последствиям для вызывающего кода, так как функция изменяет передаваемый в неё список.

2022-12-16 02:49 UTC, RealBaty commented on src/main/java/tasks/Task8.java
> +  - Не используется функция getNames, что позволяет повторно не раскладывать список в stream
Ну ведь все равно придется сначала собирать List, а потом пересобирать в Set, а это накладные расходы. И я не очень понимаю какая там может быть ещё общая логика. Но в целом асимптотика не меняется, а через getNames выглядит лучше, так что я соглашусь, что через getNames предпочтительнее. Но все же, для меня это не однозначный выбор.

2022-12-16 03:13 UTC, RealBaty commented on src/main/java/tasks/Task8.java
> +  - Подсчет реализован через count() в угоду читаемости
Возможно count быстрее работает, т. к. стримы в любом случае считают число элементов, и count() выполняется за константу (хотя filter все равно выполняется не за константу, так что асимптотика функции в целом не изменится). 
Так же благодаря тому что мы удалили ненужную приватную переменную класса, она не будет занимать место.

2022-12-20 15:11 UTC, RealBaty commented on src/main/java/tasks/Task1.java
> +      personById.put(person.getId(), person);
Подправил код в соответствии с комментарием

2022-12-20 15:11 UTC, RealBaty commented on src/main/java/tasks/Task6.java
> +                    .map(areaId -> person.getFirstName() + " - " + nameByIdAreas.get(areaId)))
Подправил код в соответствии с комментарием

2022-12-20 15:15 UTC, RealBaty commented on src/main/java/tasks/Task8.java
> +   */
Подправил код в соответствии с комментарием

2022-12-20 15:15 UTC, RealBaty commented on src/main/java/tasks/Task8.java
> +  - Улучшена читаемость за счет отсутствия вложенных циклов
Подправил код в соответствии с комментарием

2022-12-20 18:41 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  - Не используется функция getNames, что позволяет повторно не раскладывать список в stream
какая логика, скипать первый элемент например?) а вдруг потом его не надо скипать, или вообще надо по другому формат имени собирать, Или еще что

тут конечно вырожденный пример, оборачивание в hashset в целом не выносят в функцию, чисто для примера из лекции, но суть та же - не надо дублировать код, микросекунды сэкономленные на избавлении от лишней сборки в лист не стоят того)

2022-12-20 18:43 UTC, genroelgvozo approved these changes

2022-12-21 16:22 UTC, merged